Add Gemfile.lock

diff --git a/.github/workflows/gh-pages.yml b/.github/workflows/gh-pages.yml
--- a/.github/workflows/gh-pages.yml
+++ b/.github/workflows/gh-pages.yml
@@ -3,7 +3,7 @@ name: GitHub Pages
 on:
   push:
     branches:
-      - main # 빌드를 실행할 브랜치
+      - main
 
 jobs:
   build:
@@ -19,8 +19,23 @@ jobs:
           ruby-version: 3.1
           bundler-cache: true
 
+      - name: Cache gems
+        uses: actions/cache@v3
+        with:
+          path: vendor/bundle
+          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-gems-
+
       - name: Install dependencies
         run: bundle install
+
+      - name: Debug workspace
+        run: |
+          echo "Checking directories:"
+          ls -la
+          echo "Checking theme directory:"
+          ls -la hydejack-theme || echo "hydejack-theme not found!"
 
       - name: Build site
         run: bundle exec jekyll build
@@ -30,6 +45,3 @@ jobs:
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./_site
-
-      - name: Debug workspace
-        run: ls -la && ls -la hydejack-theme
